export const OPENAI_DEFAULT_MODEL = 'gpt-5.2';

export const OPENAI_PLANNING_MODEL = OPENAI_DEFAULT_MODEL;
export const OPENAI_HOST_CREATION_MODEL = OPENAI_DEFAULT_MODEL;
export const OPENAI_ORCHESTRATOR_MODEL = OPENAI_DEFAULT_MODEL;
export const OPENAI_HOST_DRAFT_MODEL = OPENAI_DEFAULT_MODEL;
